### ISSUE TITLE
Cannot Determine list of permissions used by an installed application in Android , permission is always null

### ISSUE THREAD

**Issue by mzulfaas** [nsNeruno/android_package_manager#4]
```
import 'package:android_package_manager/android_package_manager.dart';
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends MaterialApp {
  @override
  Widget get home => MyApp();
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  List<PackageInfo> _appsWithCallPermission = [];

  Future<List<PackageInfo>> getAppsWithCallPermission() async {
    List<PackageInfo> apps =  (await AndroidPackageManager().getInstalledPackages(flags:PackageInfoFlags({PMFlag.getPermissions,PMFlag.getReceivers,PMFlag.getServices,PMFlag.getProviders}))) ?? [];
    print("apps : ${apps}");
    List<PackageInfo> appsWithCallPermission = [];

    for (PackageInfo app in apps) {
      if (app.requestedPermissions!.contains("android.permission.CALL_PHONE")) {
        appsWithCallPermission.add(app);
        print(appsWithCallPermission);
      }
    }
    return appsWithCallPermission;
  }

  @override
  void initState() {
    super.initState();
    getAppsWithCallPermission().then((value) {
      setState(() {
        _appsWithCallPermission = value;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: _appsWithCallPermission.length,
        itemBuilder: (context, index) {
          return ListTile(
            title: Text("${_appsWithCallPermission[index].packageName}",style: TextStyle(color: Colors.red)),
          );
        },
      ),
    );
  }
}
```

How do I get permission used by each application?

**Comment by nsNeruno** [comment]
Thank you for reporting an issue

Given your attempts on applying those PM Flags, especially the `getPermissions` one,
I noticed a failure to parse the `requestedPermissions` from my end

I updated my integration test.
Is this the type of information what you're looking for? Here's the updated log
```
lab.neruno.android_package_manager_example | (true)
	AppInfo.name: android.app.Application
	Requested Permissions: [android.permission.INTERNET]
com.asus.zenmotion | (true)
	AppInfo.name: com.asus.zenmotion.ZenMotionApp
	Requested Permissions: [android.permission.RECEIVE_BOOT_COMPLETED, android.permission.READ_SEARCH_INDEXABLES, android.permission.INTERNET, android.permission.ACCESS_NETWORK_STATE]
```

I will apply this fix for now

**Comment by nsNeruno** [comment]
I have updated the plugin to [v0.4.0](https://pub.dev/packages/android_package_manager/changelog#040). Please kindly recheck if it actually solves your needs, thanks @mzulfaas.

**Comment by mzulfaas** [comment]
I already update to v0.4.0 but i still face the issue 

![image](https://user-images.githubusercontent.com/53118471/215319161-29b13f7c-a1cd-4f9c-acdc-8a9eca4c39bc.png)

**Comment by sanjaibalajee** [comment]
is it working now ?

**Comment by nsNeruno** [comment]
@sanjaibalajee 
Please give `v0.7.0` a try.

**Comment by nsNeruno** [comment]
Closing this issue for a while.
Looking for any feedbacks or any issues

Thank you for reporting.
Will re-open if necessary
